configured_endpoints: 47
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/casemark%2Frouter-c1eab002b6ada7b72be540869a1fa17c6ff4d4d5ca9f3db68fe92917a4ba6356.yml
openapi_spec_hash: d2bcda5d9fb0a5ffd6a3e8d9d25af41f
config_hash: c41ff7a2f505881d7696da999cacb322
